/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRouter {
    }
    interface RpdEast {
    }
    interface TestOnly {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRouterElement extends Components.AppRouter, HTMLStencilElement {
    }
    var HTMLAppRouterElement: {
        prototype: HTMLAppRouterElement;
        new (): HTMLAppRouterElement;
    };
    interface HTMLRpdEastElement extends Components.RpdEast, HTMLStencilElement {
    }
    var HTMLRpdEastElement: {
        prototype: HTMLRpdEastElement;
        new (): HTMLRpdEastElement;
    };
    interface HTMLTestOnlyElement extends Components.TestOnly, HTMLStencilElement {
    }
    var HTMLTestOnlyElement: {
        prototype: HTMLTestOnlyElement;
        new (): HTMLTestOnlyElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-router": HTMLAppRouterElement;
        "rpd-east": HTMLRpdEastElement;
        "test-only": HTMLTestOnlyElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRouter {
    }
    interface RpdEast {
    }
    interface TestOnly {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-router": AppRouter;
        "rpd-east": RpdEast;
        "test-only": TestOnly;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-router": LocalJSX.AppRouter & JSXBase.HTMLAttributes<HTMLAppRouterElement>;
            "rpd-east": LocalJSX.RpdEast & JSXBase.HTMLAttributes<HTMLRpdEastElement>;
            "test-only": LocalJSX.TestOnly & JSXBase.HTMLAttributes<HTMLTestOnlyElement>;
        }
    }
}
